version: '3.4'

services:
  peptidiff:
    image: dataset_image
    build:
      context: .
      dockerfile: ./Dockerfile_data
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 Code\Fetch_Dataset.py "]
    ports:
      - 5678:5678
