version: '3.4'

services:
  peptidiff:
    image: training_inference_image
    build:
      context: .
      dockerfile: ./Dockerfile_train
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 Code\Protein_Generation.py "]
    ports:
      - 5678:5678
